import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "../globals.css";
import { Header } from "../components/header/Header";
import { Footer } from "../components/footer/Footer";

const archivo = Archivo({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MENU_LINKS = [
  {
    href: "/login",
    label: "Ingresar",
    hasBackground: false,
  },
  {
    href: "/register",
    label: "Crear cuenta",
    hasBackground: true,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.className}  antialiased`}>
        <Header menuLinks={MENU_LINKS} />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
